### ISSUE TITLE
can not config more tasks

### ISSUE THREAD

**Issue by zhipenglin** [jmreidy/grunt-browserify#349]
can not config  more path
browserify:{
            files:[{
                expand: true,
                cwd: 'coffee/src',
                src: '**/*.coffee',
                dest: 'bin',
                ext: '.js'
            },{
                expand: true,
                cwd: 'tpl',
                src: '**/*.html',
                dest: 'bin',
                ext: '.js'
            }],
            options: {
                transform: ['coffeeify','node-underscorify']
            }
        }
run:Running "browserify:files" (browserify) task
Warning: undefined is not a function Use --force to continue.

and can not config more tasks:
browserify:{
            task_1:{
                files:{
                    expand: true,
                    cwd: 'coffee/src',
                    src: '**/*.coffee',
                    dest: 'bin',
                    ext: '.js'
                }
            },
            task_2:{
                files:{
                    expand: true,
                    cwd: 'tpl',
                    src: '**/*.html',
                    dest: 'bin',
                    ext: '.js'
                }
            },
            options: {
                transform: ['coffeeify','node-underscorify']
            }
        }
run:Running "browserify:task_1" (browserify) task
Warning: undefined is not a function Use --force to continue.

**Comment by leedorian** [comment]
Got same issue here, with glob, seems it will cause error with multiple files or tasks:
``` javascript
options: {
        debug: true,
        transform: [],
        extensions: [],
        plugin: [
            [
                'remapify',[
                    {
                        src:'**/*.js',
                        expose:'common',
                        cwd:'./src/script/common/'
                    }
                ]
            ]
        ],
        exclude: [
          'jquery',
          'src/script/common/x.js'
        ]
    },
    app: {
        files: [
            {
              expand: true,     // Enable dynamic expansion.
              cwd: 'src/script/',      // Src matches are relative to this path.
              src: ['**/*.js'], // Actual pattern(s) to match.
              dest: 'dist/js/',   // Destination path prefix.
              ext: '.js',   // Dest filepaths will have this extension.
              extDot: 'first'   // Extensions in filenames begin after the first dot
            }
        ],
        options:{
            watch:true,
            keepAlive: true,
        }
    }
```

Error:

``` bash
Fatal error: cb is not a function
TypeError: cb is not a function
    at /Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:327:20
    at onresolve (/Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:178:14)
    at /Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:173:17
    at next (/Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:457:20)
    at onpkg (/Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:499:17)
    at ReadFileContext.callback (/Users/leedorian/works/bf/bf/node_modules/grunt-browserify/node_modules/module-deps/index.js:475:29)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```
